### ISSUE TITLE
README for setting up the backend and database locally

### ISSUE THREAD

**Issue by Flinze** [idurar/starter-antd-admin-crud-auth-mern#10]
Hello,

Can you provide some details on how to setup everything up for devs to work on the project as a boilerplate? there does not seem to be any documentation in the readme on setup. Specifically for the backend and database.

Thanks.

**Comment by shabfactor** [comment]
hi, it seems the local api setup is not working the localhost:8888 is giving this error `{"success":false,"message":"Api url doesn't exist "}`

**Comment by idurar** [comment]
@shabfactor 
change it here this file : 
frontend/src/config/serverApiConfig.js

**Comment by idurar** [comment]
@Flinze 
```
## Setup backend

1) just create MongoDB Atlas accout database url 
2) change this file name .variables.env.tmp to  .variables.env
3) open  .variables.env and paste your MongoDB url here :  DATABASE=your-mongodb-url
4) npm install
5) npm setup

## Setup frontend
1) cd frontend 
2) npm install
3) change api config to loaclhost in this : src/frontend/src/config/serverApiConfig.js
 

## start server
1) npm start

## start react app
1) cd frontend
2) npm start
```

**Comment by shabfactor** [comment]
> @shabfactor change it here this file : frontend/src/config/serverApiConfig.js

@idurar 
should i change it to `http://localhost/api/` or `http://localhost:8888/api/`?

**Comment by idurar** [comment]
To http://localhost:8888/api/ , and make sure that server is running on 8888

**Comment by mituBarua** [comment]
@idurar can you please help me to setup backend??

**Comment by RathodChirag** [comment]
Hey @shabfactor, what did you change in the file :  frontend/src/config/serverApiConfig.js. because I also have same error as you

**Comment by Rathod0140** [comment]
Hey @shabfactor, what did you change in the file : frontend/src/config/serverApiConfig.js. because I also have same error as you
